{
  "hash": "72074e3d1d55f145d1655be88ffd2570",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The Hidden Cost of a Rate Hike\"\nsubtitle: \"How Higher Mortgage Rates Shrink Homebuying Power\"\nauthor: \"Scarlett\"\ndate: \"2026-09-21\"\ndescription: \"A reproducible web-scraping analysis of how monetary tightening reaches household mortgage budgets.\"\ncategories: [web scraping, monetary policy, housing, mortgage rates, R]\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-summary: \"Show the reproducible R code\"\n    code-tools: true\n    df-print: paged\n    fig-width: 8\n    fig-height: 5\nexecute:\n  warning: false\n  message: false\n  echo: true\n  freeze: auto\neditor: source\n---\n\n\n\n\n\n\n\nOn September 16, 2026, the Federal Open Market Committee (FOMC) raised its federal-funds target range by 25 basis points to 3.75%--4.00%. That decision immediately changed short-term benchmark rates, but homebuyers do not borrow overnight: they usually finance a purchase for 15 or 30 years. This post asks a practical question:\n\n> **How did mortgage financing conditions change around the September meeting, and how much homebuying power did the observed rate change remove?**\n\nThe answer matters because buyers often shop by listing price when the binding constraint is actually monthly cash flow. I combine scraped policy, mortgage, and housing-market information with standard mortgage mathematics to translate a rate movement into dollars a household can use.\n\n## Research design: from websites to a decision\n\nThe analysis follows a transparent pipeline:\n\n1. **Collect:** scrape four public webpages with `rvest` and cache one dated HTML copy of each page.\n2. **Clean:** convert table headings into dates, percentage strings into decimals, and price text into a numeric dollar value.\n3. **Validate:** require the policy and mortgage observations used in the comparison to be present and nonmissing.\n4. **Calculate:** apply the fixed-rate mortgage annuity formula under explicit assumptions.\n5. **Decide:** convert the estimates into budget and stress-testing recommendations for prospective buyers.\n\n### Sources and ethical access\n\n| Source | Scraped information | Role in the analysis |\n|---|---|---|\n| Federal Reserve FOMC statement | Announced target range | Confirms the policy event |\n| Federal Reserve H.15 table | Effective federal-funds and bank prime rates | Measures immediate short-rate pass-through |\n| Freddie Mac PMMS archive | Weekly 30- and 15-year mortgage rates | Measures household financing conditions |\n| Census New Residential Sales | Median new-home sales price | Defines a representative purchase scenario |\n\nAll four pages are public and require no login, CAPTCHA, paywall, or access workaround. The script makes at most one request per source when a cached file is absent, waits before requesting, identifies the academic user agent, and reuses local HTML thereafter. This both limits server load and fixes the source vintage for reproducibility.\n\n## Data collection, cleaning, and validation\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# FOMC statement ---------------------------------------------------------\nfomc_page <- read_cached_page(\n  \"https://www.federalreserve.gov/newsevents/pressreleases/monetary20260916a.htm\",\n  \"fomc_2026-09-16.html\"\n)\n\nfomc_text <- fomc_page |>\n  html_elements(\"#article p\") |>\n  html_text2() |>\n  str_squish() |>\n  str_c(collapse = \" \")\n\nif (!str_detect(fomc_text, \"3-3/4 to 4 percent\")) {\n  stop(\"The expected target range was not found in the FOMC statement.\")\n}\n\n# Federal Reserve H.15 --------------------------------------------------\nh15_page <- read_cached_page(\n  \"https://www.federalreserve.gov/releases/h15/\",\n  \"h15_2026-09-21.html\"\n)\n\nh15 <- h15_page |>\n  html_element(\"table\") |>\n  html_table(fill = TRUE) |>\n  clean_names()\n\nh15_long <- h15 |>\n  pivot_longer(\n    -instruments,\n    names_to = \"date_label\",\n    values_to = \"rate_text\"\n  ) |>\n  mutate(\n    date_text = date_label |>\n      str_remove(\"^x\") |>\n      str_replace_all(\"_\", \" \"),\n    date = parse_date_time(\n      date_text,\n      orders = \"Y b d\",\n      locale = \"C\",\n      quiet = TRUE\n    ) |>\n      as_date(),\n    rate = parse_number(as.character(rate_text)) / 100\n  )\n\npolicy_snapshot <- h15_long |>\n  filter(\n    date %in% ymd(c(\"2026-09-16\", \"2026-09-17\")),\n    str_detect(\n      instruments,\n      \"Federal funds \\\\(effective\\\\)|Bank prime loan\"\n    )\n  ) |>\n  mutate(\n    series = if_else(\n      str_detect(instruments, \"Federal funds\"),\n      \"Effective federal funds rate\",\n      \"Bank prime rate\"\n    )\n  ) |>\n  select(date, series, rate) |>\n  arrange(series, date)\n\nif (nrow(policy_snapshot) != 4 || anyNA(policy_snapshot$rate)) {\n  stop(\n    paste0(\n      \"The four required H.15 observations were not recovered. \",\n      \"Use the dated h15_2026-09-21.html snapshot.\"\n    )\n  )\n}\n\n# Freddie Mac PMMS ------------------------------------------------------\npmms_page <- read_cached_page(\n  \"https://www.freddiemac.com/pmms/archive\",\n  \"pmms_2026-09-21.html\"\n)\n\npmms_dates <- pmms_page |>\n  html_elements(\"p.lead strong\") |>\n  html_text2() |>\n  str_squish() |>\n  mdy(locale = \"C\", quiet = TRUE)\n\npmms_tables <- pmms_page |>\n  html_elements(\"table.hover\") |>\n  html_table(fill = TRUE)\n\nif (\n  length(pmms_dates) == 0 ||\n  length(pmms_dates) != length(pmms_tables) ||\n  anyNA(pmms_dates)\n) {\n  stop(\"Freddie Mac dates and tables could not be matched reliably.\")\n}\n\npmms <- map2_dfr(pmms_dates, pmms_tables, function(obs_date, tab) {\n  clean_tab <- clean_names(tab)\n\n  if (!all(c(\"x30_yr_frm\", \"x15_yr_frm\") %in% names(clean_tab))) {\n    stop(\"Expected PMMS mortgage-rate columns were not found.\")\n  }\n\n  clean_tab |>\n    transmute(\n      date = as_date(obs_date),\n      mortgage_30y = percent_to_decimal(x30_yr_frm),\n      mortgage_15y = percent_to_decimal(x15_yr_frm)\n    )\n}) |>\n  filter(is.finite(mortgage_30y), is.finite(mortgage_15y)) |>\n  distinct(date, .keep_all = TRUE) |>\n  arrange(date)\n\nanalysis_rates <- pmms |>\n  filter(date %in% ymd(c(\"2026-09-10\", \"2026-09-17\"))) |>\n  arrange(date)\n\nif (nrow(analysis_rates) != 2 || anyNA(analysis_rates$mortgage_30y)) {\n  stop(\n    paste0(\n      \"The September 10 and September 17 PMMS observations were not both found. \",\n      \"Use the dated pmms_2026-09-21.html snapshot.\"\n    )\n  )\n}\n\n# Census New Residential Sales -----------------------------------------\ncensus_page <- read_cached_page(\n  \"https://www.census.gov/construction/nrs/current/index.html\",\n  \"census_nrs_2026-09-21.html\"\n)\n\ncensus_text <- census_page |>\n  html_element(\"body\") |>\n  html_text2() |>\n  str_squish()\n\nmedian_price_match <- str_match(\n  census_text,\n  regex(\n    \"median sales price[^$]{0,250}\\\\$([0-9,]+)\",\n    ignore_case = TRUE\n  )\n)\n\nmedian_price <- parse_number(median_price_match[1, 2])\n\nif (!is.finite(median_price) || median_price <= 0) {\n  stop(\"A valid Census median sales price was not extracted.\")\n}\n\n# Save cleaned, analysis-ready data ------------------------------------\nwrite_csv(pmms, file.path(processed_dir, \"pmms_clean.csv\"))\nwrite_csv(policy_snapshot, file.path(processed_dir, \"policy_snapshot.csv\"))\n\ncensus_snapshot <- tibble(\n  snapshot_date = ymd(\"2026-09-21\"),\n  median_new_home_price = median_price\n)\nwrite_csv(census_snapshot, file.path(processed_dir, \"census_price_snapshot.csv\"))\n```\n:::\n\n\n\n\n\nThe raw webpages contain dates embedded in headings, interest rates stored as character strings with percent signs, and the Census price embedded in prose. Cleaning therefore changes representation, not economic meaning: `6.95%` becomes `0.0695` for calculation, comma-separated dollar text becomes a number, and the dated columns in H.15 become a tidy date-series-rate table. The validation checks deliberately stop the render rather than silently produce a chart from incomplete observations.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrate_before <- analysis_rates$mortgage_30y[[1]]\nrate_after <- analysis_rates$mortgage_30y[[2]]\nrate_change_bp <- (rate_after - rate_before) * 10000\n\neffr_before <- policy_snapshot |>\n  filter(\n    series == \"Effective federal funds rate\",\n    date == ymd(\"2026-09-16\")\n  ) |>\n  pull(rate)\n\neffr_after <- policy_snapshot |>\n  filter(\n    series == \"Effective federal funds rate\",\n    date == ymd(\"2026-09-17\")\n  ) |>\n  pull(rate)\n\nprime_before <- policy_snapshot |>\n  filter(series == \"Bank prime rate\", date == ymd(\"2026-09-16\")) |>\n  pull(rate)\n\nprime_after <- policy_snapshot |>\n  filter(series == \"Bank prime rate\", date == ymd(\"2026-09-17\")) |>\n  pull(rate)\n\nmedian_loan <- 0.80 * median_price\npayment_before <- mortgage_payment(median_loan, rate_before)\npayment_after <- mortgage_payment(median_loan, rate_after)\nmonthly_payment_change <- payment_after - payment_before\nannual_payment_change <- 12 * monthly_payment_change\npayment_change_pct <- payment_after / payment_before - 1\n\nbefore_label <- paste0(\"Before: \", percent(rate_before, accuracy = 0.01))\nafter_label <- paste0(\"After: \", percent(rate_after, accuracy = 0.01))\n\nresult_summary <- tibble(\n  Measure = c(\n    \"Effective federal-funds rate\",\n    \"Bank prime rate\",\n    \"30-year fixed mortgage rate\"\n  ),\n  Before = c(effr_before, prime_before, rate_before),\n  After = c(effr_after, prime_after, rate_after),\n  `Change (basis points)` = 10000 * (After - Before)\n)\n```\n:::\n\n::: {#tbl-rate-summary .cell tbl-cap='Policy and borrowing rates around the September 16 FOMC decision'}\n\n```{.r .cell-code}\nresult_summary |>\n  mutate(\n    Before = percent(Before, accuracy = 0.01),\n    After = percent(After, accuracy = 0.01),\n    `Change (basis points)` = round(`Change (basis points)`)\n  ) |>\n  knitr::kable(align = c(\"l\", \"r\", \"r\", \"r\"))\n```\n\n::: {.cell-output-display}\n\n\n|Measure                      | Before| After| Change (basis points)|\n|:----------------------------|------:|-----:|---------------------:|\n|Effective federal-funds rate |  3.63%| 3.88%|                    25|\n|Bank prime rate              |  6.75%| 7.00%|                    25|\n|30-year fixed mortgage rate  |  6.76%| 6.95%|                    19|\n\n\n:::\n:::\n\n\n\n\n\n## Finding 1: the transmission was immediate, but not one-for-one\n\nThe effective federal-funds rate moved from 3.63% to 3.88%, while the bank prime rate moved from 6.75% to 7.00%. These short-term rates followed the 25-basis-point policy move closely.\n\nThe 30-year mortgage rate behaved differently. It rose from 6.76% on September 10 to 6.95% on September 17, a 19-basis-point weekly increase. Figure 1 also shows that mortgage rates had been rising before the announcement. That is economically sensible because mortgage rates reflect expected future short rates, long-term yields, and mortgage-backed-security risk:\n\n$$\nr_t^{mortgage}\n\\approx\ny_t^{10Y}+\\text{MBS spread}_t.\n$$\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenglish_month_breaks <- ymd(sprintf(\"2026-%02d-01\", 1:9))\n\np1 <- pmms |>\n  filter(date >= ymd(\"2026-01-01\"), date <= ymd(\"2026-09-17\")) |>\n  ggplot(aes(date, mortgage_30y)) +\n  geom_line(linewidth = 0.9, color = \"#24496e\") +\n  geom_vline(\n    xintercept = ymd(\"2026-09-16\"),\n    linetype = \"dashed\",\n    color = \"#b24c3d\",\n    linewidth = 0.7\n  ) +\n  geom_point(data = analysis_rates, size = 3.2, color = \"#b24c3d\") +\n  geom_text(\n    data = analysis_rates,\n    aes(label = percent(mortgage_30y, accuracy = 0.01)),\n    vjust = -0.9,\n    color = \"#8f382d\",\n    size = 3.6\n  ) +\n  scale_y_continuous(labels = percent_format(accuracy = 0.1)) +\n  scale_x_date(\n    breaks = english_month_breaks,\n    labels = month.abb[1:9],\n    limits = ymd(c(\"2026-01-01\", \"2026-09-22\")),\n    expand = expansion(mult = c(0.01, 0.02))\n  ) +\n  labs(\n    title = paste0(\n      \"The 30-year mortgage rate reached \",\n      percent(rate_after, accuracy = 0.01)\n    ),\n    subtitle = \"Weekly national average, January-September 2026\",\n    x = NULL,\n    y = \"30-year fixed mortgage rate\"\n  )\n\np1\nggsave(\n  file.path(figure_dir, \"mortgage-rate-trend.png\"),\n  p1,\n  width = 8,\n  height = 5,\n  dpi = 300\n)\n```\n\n::: {.cell-output-display}\n![Figure 1. Weekly U.S. 30-year fixed mortgage rate. The red points are the September 10 and 17 comparison observations; the dashed line marks the September 16 FOMC decision. Source: Freddie Mac PMMS; author's calculations.](index_files/figure-html/fig-mortgage-trend-1.png){#fig-mortgage-trend width=768}\n:::\n:::\n\n\n\n\n\nThe figure documents timing, not causality. A 19-basis-point weekly change is not a causal estimate of the FOMC announcement because markets anticipated the meeting and other rate components moved simultaneously. A causal design would require a narrower high-frequency event window and market instruments observed around the exact announcement time.\n\n## Finding 2: a small rate change compounds over 360 payments\n\nFor loan principal $L$, monthly rate $r$, and $N=360$ payments, monthly principal and interest equal\n\n$$\nM=L\\frac{r(1+r)^N}{(1+r)^N-1}.\n$$\n\nThis nonlinear annuity formula converts the observed mortgage-rate change into a household cash-flow effect.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan_values <- c(300000, 400000, 500000)\n\npayment_grid <- crossing(\n  mortgage_rate = seq(0.04, 0.08, by = 0.0005),\n  loan = loan_values\n) |>\n  mutate(monthly_payment = mortgage_payment(loan, mortgage_rate))\n\np2 <- ggplot(\n  payment_grid,\n  aes(mortgage_rate, monthly_payment, color = factor(loan))\n) +\n  geom_line(linewidth = 1) +\n  geom_vline(\n    xintercept = rate_before,\n    linetype = \"dotted\",\n    linewidth = 0.8,\n    color = \"#555555\"\n  ) +\n  geom_vline(\n    xintercept = rate_after,\n    linetype = \"dashed\",\n    linewidth = 0.8,\n    color = \"#b24c3d\"\n  ) +\n  annotate(\n    \"text\",\n    x = rate_before,\n    y = max(payment_grid$monthly_payment) * 0.985,\n    label = before_label,\n    angle = 90,\n    hjust = 1,\n    vjust = 1.3,\n    size = 3.2\n  ) +\n  annotate(\n    \"text\",\n    x = rate_after,\n    y = max(payment_grid$monthly_payment) * 0.985,\n    label = after_label,\n    angle = 90,\n    hjust = 1,\n    vjust = -0.4,\n    color = \"#8f382d\",\n    size = 3.2\n  ) +\n  scale_x_continuous(labels = percent_format(accuracy = 0.1)) +\n  scale_y_continuous(labels = dollar_format()) +\n  scale_color_manual(\n    values = c(\"#3f7d5c\", \"#c17b31\", \"#8d4773\"),\n    breaks = as.character(loan_values),\n    labels = dollar(loan_values)\n  ) +\n  labs(\n    title = \"Small rate changes compound over 360 payments\",\n    subtitle = \"Monthly principal and interest by loan size\",\n    x = \"Mortgage rate\",\n    y = \"Monthly payment\",\n    color = \"Loan amount\"\n  )\n\np2\nggsave(\n  file.path(figure_dir, \"payment-curves.png\"),\n  p2,\n  width = 8,\n  height = 5,\n  dpi = 300\n)\n```\n\n::: {.cell-output-display}\n![Figure 2. Monthly principal and interest for a 30-year fixed mortgage. The dotted and dashed lines mark the observed before and after rates. Taxes, insurance, fees, and maintenance are excluded.](index_files/figure-html/fig-payment-curves-1.png){#fig-payment-curves width=768}\n:::\n:::\n\n\n\n\n\nUsing the scraped Census median new-home price of $393,800 and a 20% down payment implies a $315,040 mortgage. Monthly principal and interest rise from $2,045 to $2,085: an increase of $40 per month, or $480 per year. In percentage terms, the payment rises by 1.95% even though the mortgage rate rises by only 19 basis points.\n\nFigure 2 also reveals scale exposure. The same rate increase adds more dollars to the payment on a larger loan because the rate applies to a larger principal. This is why highly leveraged buyers are more sensitive to monetary tightening.\n\n## Finding 3: fixed-budget buyers lose purchasing power\n\nThe more decision-relevant calculation holds the monthly budget fixed and solves the annuity formula for the maximum loan:\n\n$$\nL_{max}=M\\frac{1-(1+r)^{-N}}{r}.\n$$\n\nWith a 20% down payment, maximum home price is $L_{max}/0.80$.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperiod_levels <- c(before_label, after_label)\n\nbudget_results <- crossing(\n  monthly_budget = c(2000, 2500, 3000),\n  period = period_levels\n) |>\n  mutate(\n    period = factor(period, levels = period_levels),\n    rate = if_else(period == before_label, rate_before, rate_after),\n    max_home_price = max_loan(monthly_budget, rate) / 0.80\n  )\n\nbudget_summary <- budget_results |>\n  select(monthly_budget, period, max_home_price) |>\n  pivot_wider(names_from = period, values_from = max_home_price) |>\n  mutate(\n    dollar_loss = .data[[after_label]] - .data[[before_label]],\n    percent_loss = .data[[after_label]] / .data[[before_label]] - 1\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np3 <- ggplot(\n  budget_results,\n  aes(factor(monthly_budget), max_home_price, fill = period)\n) +\n  geom_col(position = position_dodge(width = 0.75), width = 0.65) +\n  geom_text(\n    aes(label = dollar(max_home_price, accuracy = 1000)),\n    position = position_dodge(width = 0.75),\n    vjust = -0.35,\n    size = 3.6\n  ) +\n  scale_y_continuous(\n    labels = dollar_format(),\n    expand = expansion(mult = c(0, 0.12))\n  ) +\n  scale_fill_manual(\n    values = c(\"#7396b8\", \"#c65d45\"),\n    breaks = period_levels\n  ) +\n  labs(\n    title = \"Higher rates reduce homebuying power\",\n    subtitle = \"Maximum price supported by the same monthly budget\",\n    x = \"Monthly principal-and-interest budget\",\n    y = \"Maximum home price\",\n    fill = NULL\n  ) +\n  theme(legend.position = \"top\")\n\np3\nggsave(\n  file.path(figure_dir, \"buying-power.png\"),\n  p3,\n  width = 8,\n  height = 5,\n  dpi = 300\n)\n```\n\n::: {.cell-output-display}\n![Figure 3. Maximum home price supported by a fixed principal-and-interest budget. Assumptions: 30-year fixed mortgage, 20% down payment, no taxes, insurance, fees, or maintenance.](index_files/figure-html/fig-buying-power-1.png){#fig-buying-power width=768}\n:::\n:::\n\n::: {#tbl-buying-power .cell tbl-cap='Change in maximum affordable home price after the observed mortgage-rate increase'}\n\n```{.r .cell-code}\nbudget_summary |>\n  transmute(\n    `Monthly P&I budget` = dollar(monthly_budget),\n    `Maximum price before` = dollar(.data[[before_label]], accuracy = 1),\n    `Maximum price after` = dollar(.data[[after_label]], accuracy = 1),\n    `Dollar change` = dollar(dollar_loss, accuracy = 1),\n    `Percent change` = percent(percent_loss, accuracy = 0.01)\n  ) |>\n  knitr::kable(align = c(\"r\", \"r\", \"r\", \"r\", \"r\"))\n```\n\n::: {.cell-output-display}\n\n\n| Monthly P&I budget| Maximum price before| Maximum price after| Dollar change| Percent change|\n|------------------:|--------------------:|-------------------:|-------------:|--------------:|\n|             $2,000|             $385,052|            $377,673|       -$7,379|         -1.92%|\n|             $2,500|             $481,315|            $472,092|       -$9,223|         -1.92%|\n|             $3,000|             $577,578|            $566,510|      -$11,068|         -1.92%|\n\n\n:::\n:::\n\n\n\n\n\nAt a $2,000 monthly principal-and-interest budget, maximum price falls by approximately $7,379. At a $3,000 budget, the dollar loss grows to approximately $11,068. The percentage reduction is 1.92% at every budget because the maximum-loan formula is linear in the monthly budget when the rate and maturity are fixed.\n\n## Decision rule and stress test\n\nThe observed weekly change is modest compared with the uncertainty a buyer may face between preapproval and closing. A practical decision rule is therefore to choose a home price that remains affordable under a higher-rate scenario, not merely at today's quoted rate.\n\n\n\n\n\n::: {#tbl-stress-test .cell tbl-cap='Stress test for a $2,500 monthly principal-and-interest budget'}\n\n```{.r .cell-code}\nstress_test <- tibble(\n  Scenario = c(\n    \"Observed before rate\",\n    \"Observed after rate\",\n    \"After rate + 50 bp\",\n    \"After rate + 100 bp\"\n  ),\n  mortgage_rate = c(\n    rate_before,\n    rate_after,\n    rate_after + 0.005,\n    rate_after + 0.010\n  )\n) |>\n  mutate(\n    maximum_loan = max_loan(2500, mortgage_rate),\n    maximum_home_price = maximum_loan / 0.80\n  )\n\nstress_test |>\n  transmute(\n    Scenario,\n    `Mortgage rate` = percent(mortgage_rate, accuracy = 0.01),\n    `Maximum loan` = dollar(maximum_loan, accuracy = 1),\n    `Maximum home price` = dollar(maximum_home_price, accuracy = 1)\n  ) |>\n  knitr::kable(align = c(\"l\", \"r\", \"r\", \"r\"))\n```\n\n::: {.cell-output-display}\n\n\n|Scenario             | Mortgage rate| Maximum loan| Maximum home price|\n|:--------------------|-------------:|------------:|------------------:|\n|Observed before rate |         6.76%|     $385,052|           $481,315|\n|Observed after rate  |         6.95%|     $377,673|           $472,092|\n|After rate + 50 bp   |         7.45%|     $359,302|           $449,127|\n|After rate + 100 bp  |         7.95%|     $342,334|           $427,917|\n\n\n:::\n:::\n\n\n\n\n\nA prospective buyer should therefore:\n\n1. set a sustainable **all-in** monthly housing limit before searching by price;\n2. reserve part of that limit for property tax, insurance, HOA fees, and maintenance, because the figures above include only principal and interest;\n3. stress-test affordability at least 50--100 basis points above the current quote; and\n4. treat future refinancing as an option, not as a condition required to make today's purchase affordable.\n\n## What this analysis can and cannot establish\n\nThe evidence supports a cash-flow conclusion, not a causal monetary-policy estimate. PMMS is a national weekly average, while an individual quote depends on credit score, loan-to-value ratio, points, geography, and loan type. The Census statistic describes newly built homes rather than all transactions. Most importantly, comparing one week before and after the meeting cannot isolate the surprise component of monetary policy from other news.\n\nA deeper follow-up could merge daily Treasury yields and mortgage-backed-security spreads, separate expected policy from announcement surprises, and compare metro areas with different price levels. That extension would test whether a given rate shock has larger dollar effects in expensive markets and whether changing spreads amplify or absorb policy-rate movements.\n\n## Takeaway\n\nThe September episode illustrates a three-stage transmission mechanism: the policy decision moved short-term benchmarks, mortgage markets repriced long-term household credit, and the higher financing rate reduced the present value of the home a fixed monthly budget could support. For buyers, the relevant price of a house is therefore not its listing price alone. It is the long-term cash-flow commitment jointly created by the price, down payment, and financing rate.\n\n## Reproducibility\n\nThe repository should retain the following structure:\n\n```text\nblog/posts/post2/index.qmd\ndata/raw/                         # dated HTML snapshots\ndata/processed/                   # cleaned CSV files created by this post\nfigures/                          # 300-dpi figures created by this post\nREADME.md                         # packages and replication steps\n```\n\nTo reproduce the post, install the listed packages once, open the Quarto project, keep `refresh_data <- FALSE`, and render the website. The post programmatically creates the cleaned CSV files and figures; no reported result is manually copied into the prose.\n\n## Sources\n\n- Board of Governors of the Federal Reserve System. “Federal Reserve Issues FOMC Statement,” September 16, 2026. <https://www.federalreserve.gov/newsevents/pressreleases/monetary20260916a.htm>\n- Board of Governors of the Federal Reserve System. *H.15 Selected Interest Rates*. <https://www.federalreserve.gov/releases/h15/>\n- Freddie Mac. *Primary Mortgage Market Survey Archive*. <https://www.freddiemac.com/pmms/archive>\n- U.S. Census Bureau and U.S. Department of Housing and Urban Development. *New Residential Sales*. <https://www.census.gov/construction/nrs/current/index.html>\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}